In [1]:
import torch
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
print(np.__version__)

cuda
1.19.5


In [2]:
%%time
start_time = time.time()
#matrix operations start
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time: .10f}")

 0.0180003643
CPU times: total: 0 ns
Wall time: 18 ms


Exploring how GPU performs better in training through Parallel Processing

In [4]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device) # pushes random matrix in GPU
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100).cpu()  # Ensure tensor is on CPU
np_rand2 = torch.rand(100, 100, 100, 100).cpu()  # Ensure tensor is on CPU

start_time = time.time()

rand = (torch_rand1 @ torch_rand2) # @ is used to multiply in pytorch

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time: .8f}")

# For checking CPU performance using Numpy
start_time = time.time()

# Convert torch tensors to numpy arrays
rand = np.multiply(np_rand1.numpy(), np_rand2.numpy())
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time: .8f}")

 0.04920864
 0.12554598


In [7]:
# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])

# Draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 0, 1])


In [8]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [9]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [10]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [13]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [14]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

Transposing function in Pytorch

In [15]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

Stacking the tensors along a new dimension

In [16]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

NN Linear Model

In [17]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([ -3.2216, -15.4616,   0.5656], grad_fn=<SqueezeBackward4>)


Applying Softmax Function

In [18]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0, 2.0, 3.0])

softmax_output = F.softmax(tensor1, dim=0)
print(softmax_output) 

tensor([0.0900, 0.2447, 0.6652])
